feat(ab): Add OECORE_TARGET_ARCH to CLI (#151)
Upstream does not have this flag, but I think that's OK because users of
the upstream tool already expect that they have to set
OECORE_TARGET_ARCH and when they do they don't have to provide the flag,
so our binary still works as a drop in replacement. Prompted by me being
confused by this not-so-helpful output when I forgot to set
OECORE_TARGET_ARCH:

```
Error: environment variable not found
```