fix(vapix): Skip serializing comment when none in ssh 1
Because this would fail with an error like:

```
Error: Failed to add SSH user

Caused by:
    (5) Validation error: Trying to add to 'users' with invalid data: null is not of type "string" (path: /comment)
```