chore: Use https for git submodule
The installation instructions in the README no longer works:

```
error: failed to update submodule `crates/vapix/tests/cassette_tests`
```

I think the reason is that Cargo tries to fetch submodules but since it
uses `libgit2` it is not aware of the credentials needed to
authenticate with SSH.